CREATE TABLE contract_user (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) DEFAULT 'anonymous' NOT NULL UNIQUE,
    email VARCHAR2(100),
    active NUMBER(1) DEFAULT 1 NOT NULL,
    quota NUMBER(10, 2),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_contract_user PRIMARY KEY (id)
);
COMMENT ON TABLE contract_user IS 'Contract users';
COMMENT ON COLUMN contract_user.username IS 'Contract login name';

CREATE TABLE contract_group (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    CONSTRAINT pk_contract_group PRIMARY KEY (id)
);

CREATE TABLE contract_external (
    account_id VARCHAR2(40) PRIMARY KEY,
    display_name VARCHAR2(100) NOT NULL
);

CREATE TABLE contract_address (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    city VARCHAR2(50),
    CONSTRAINT pk_contract_address PRIMARY KEY (id),
    CONSTRAINT fk_contract_address_user FOREIGN KEY (user_id) REFERENCES contract_user(id)
);

CREATE TABLE contract_composite (
    tenant_id NUMBER NOT NULL,
    record_id NUMBER NOT NULL,
    role_name VARCHAR2(50),
    CONSTRAINT pk_contract_composite PRIMARY KEY (tenant_id, record_id)
);

CREATE VIEW contract_user_view AS
SELECT id, username, email FROM contract_user;

INSERT INTO contract_user (username, email, active, quota)
VALUES ('alice', 'alice@example.com', 1, 10.50);
INSERT INTO contract_user (username, email, active, quota)
VALUES ('bob', NULL, 0, 20.00);
INSERT INTO contract_group (name) VALUES ('developers');
INSERT INTO contract_address (user_id, city) VALUES (1, 'Bratislava');
INSERT INTO contract_composite (tenant_id, record_id, role_name) VALUES (1, 1, 'owner');
INSERT INTO contract_external (account_id, display_name) VALUES ('existing', 'Existing account');
