-- Reproduction schema for WP 12165: Conndev generates ConnectorObjectReference without roleInReference.
-- Exact DDL from the work package: two schemas, same-named `users` tables, and an `accounts`
-- table with a surrogate PK plus a single FK (no FK in the PK).

DROP SCHEMA IF EXISTS schema_a CASCADE;
DROP SCHEMA IF EXISTS schema_b CASCADE;
CREATE SCHEMA schema_a;
CREATE SCHEMA schema_b;

CREATE TABLE schema_a.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_schema_a_users
        PRIMARY KEY (id),

    CONSTRAINT uq_schema_a_users_username
        UNIQUE (username)
);

CREATE TABLE schema_b.users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    login TEXT NOT NULL,
    display_name VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    external_id VARCHAR(64) NOT NULL,

    CONSTRAINT pk_schema_b_users
        PRIMARY KEY (user_id),

    CONSTRAINT uq_schema_b_users_login
        UNIQUE (login),

    CONSTRAINT uq_schema_b_users_external_id
        UNIQUE (external_id),

    CONSTRAINT chk_schema_b_users_status
        CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED'))
);

CREATE TABLE schema_b.accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    system_name VARCHAR(100) NOT NULL,
    account_name VARCHAR(150) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_schema_b_accounts
        PRIMARY KEY (account_id),

    CONSTRAINT uq_schema_b_accounts_system_account
        UNIQUE (system_name, account_name),

    CONSTRAINT fk_schema_b_accounts_user
        FOREIGN KEY (user_id)
        REFERENCES schema_b.users(user_id)
        ON DELETE CASCADE
);

INSERT INTO schema_a.users (
    username,
    email,
    active
)
VALUES (
    'asmith',
    'alice.smith@example.com',
    TRUE
);

INSERT INTO schema_b.users (
    login,
    display_name,
    status,
    external_id
)
VALUES (
    'alice.legacy',
    'Alice Smith',
    'ACTIVE',
    'LEGACY-1001'
);

INSERT INTO schema_b.accounts (
    user_id,
    system_name,
    account_name,
    enabled
)
SELECT
    user_id,
    'ERP',
    'asmith',
    TRUE
FROM schema_b.users
WHERE login = 'alice.legacy';
